import type { Metadata } from "next";
import QueryProvider from "@src/components/QueryProvider";
import "@src/styles/global.css";
import MuiThemeProvider from "@src/theme/MuiThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <MuiThemeProvider>
        <html lang="en">
          <body>{children}</body>
        </html>
      </MuiThemeProvider>
    </QueryProvider>
  );
}
